services:
  - type: web
    name: researchers-degree-of-separation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENALEX_KEY
        sync: false
